from typing import Any

categories: list[list[dict[str, Any]]] = [
    [
        {
            "Id":"CameraNavigation",
            "IconId":"CameraIcon",
            "TitleId":"wiki.category.CameraNavigation",
            "RequiredUpgradeIds":[],
            "RequiredMechanicIds":[]
        },
        {
            "Id":"Placement",
            "IconId":"PlacementAndSelectionIcon",
            "TitleId":"wiki.category.Placement",
            "RequiredUpgradeIds":[],
            "RequiredMechanicIds":[]
        },
        {
            "Id":"Belts",
            "IconId":"ShapeTransportGroup",
            "TitleId":"wiki.category.Belts",
            "RequiredUpgradeIds":[],
            "RequiredMechanicIds":[]
        },
        {
            "Id":"Blueprints",
            "IconId":"Blueprints",
            "TitleId":"wiki.category.Blueprints",
            "RequiredUpgradeIds":[],
            "RequiredMechanicIds":[]
        },
        {
            "Id":"Shapes",
            "IconId":"ShapeCategory",
            "TitleId":"wiki.category.Shapes",
            "RequiredUpgradeIds":[],
            "RequiredMechanicIds":[]
        },
        {
            "Id":"Processing",
            "IconId":"BuildingsGeneralIcon",
            "TitleId":"wiki.category.Processing",
            "RequiredUpgradeIds":[],
            "RequiredMechanicIds":[]
        },
        {
            "Id":"Research",
            "IconId":"InnovationCategory",
            "TitleId":"wiki.category.Research",
            "RequiredUpgradeIds":[],
            "RequiredMechanicIds":[]
        },
        {
            "Id":"Islands",
            "IconId":"PlatformsCategory",
            "TitleId":"wiki.category.Islands",
            "RequiredUpgradeIds":[],
            "RequiredMechanicIds":[]
        },
        {
            "Id":"Fluids",
            "IconId":"FluidsCategory",
            "TitleId":"wiki.category.Fluids",
            "RequiredUpgradeIds":[],
            "RequiredMechanicIds":[]
        },
        {
            "Id":"Trains",
            "IconId":"TrainsCategory",
            "TitleId":"wiki.category.Trains",
            "RequiredUpgradeIds":[],
            "RequiredMechanicIds":[]
        },
        {
            "Id":"TradeStations",
            "IconId":"ConverterCategory",
            "TitleId":"wiki.category.TradeStations",
            "RequiredUpgradeIds":[],
            "RequiredMechanicIds":[]
        },
        {
            "Id":"Wires",
            "IconId":"SignalsCategory",
            "TitleId":"wiki.category.Wires",
            "RequiredUpgradeIds":[],
            "RequiredMechanicIds":[]
        },
        {
            "Id":"VortexLTD",
            "IconId":"ConverterVortex",
            "TitleId":"wiki.category.VortexLTD",
            "RequiredUpgradeIds":[],
            "RequiredMechanicIds":[]
        },
        {
            "Id":"Misc",
            "IconId":"Folder",
            "TitleId":"wiki.category.Misc",
            "RequiredUpgradeIds":[],
            "RequiredMechanicIds":[]
        }
    ]
]

wiki_entries: list[list[dict[str, Any]]] = [
    [
        {
            "EntryId":"WKTutorialWelcome",
            "CategoryId":"Misc",
            "RequiredMechanicIds":[],
            "RequiredUpgradeIds":[]
        },
        {
            "EntryId":"WKCameraNavigation_Movement",
            "CategoryId":"CameraNavigation",
            "RequiredMechanicIds":[],
            "RequiredUpgradeIds":[]
        },
        {
            "EntryId":"WKCameraNavigation_Zoom",
            "CategoryId":"CameraNavigation",
            "RequiredMechanicIds":[],
            "RequiredUpgradeIds":[]
        },
        {
            "EntryId":"WKCameraNavigation_Rotation",
            "CategoryId":"CameraNavigation",
            "RequiredMechanicIds":[],
            "RequiredUpgradeIds":[]
        },
        {
            "EntryId":"WKCameraNavigation_CameraSnapping",
            "CategoryId":"CameraNavigation",
            "RequiredMechanicIds":[],
            "RequiredUpgradeIds":[]
        },
        {
            "EntryId":"WKCameraNavigation_SwitchingFloors",
            "CategoryId":"CameraNavigation",
            "RequiredMechanicIds":[],
            "RequiredUpgradeIds":[]
        },
        {
            "EntryId":"WKCameraNavigation_JumpToHub",
            "CategoryId":"CameraNavigation",
            "RequiredMechanicIds":[],
            "RequiredUpgradeIds":[]
        },
        {
            "EntryId":"WKCameraNavigation_Visualizations",
            "CategoryId":"CameraNavigation",
            "RequiredMechanicIds":[],
            "RequiredUpgradeIds":[]
        },
        {
            "EntryId":"WKCameraNavigation_MapMarkers",
            "CategoryId":"CameraNavigation",
            "RequiredMechanicIds":[],
            "RequiredUpgradeIds":[]
        },
        {
            "EntryId":"WKPlacement_Placement",
            "CategoryId":"Placement",
            "RequiredMechanicIds":[],
            "RequiredUpgradeIds":[]
        },
        {
            "EntryId":"WKPlacement_Rotation",
            "CategoryId":"Placement",
            "RequiredMechanicIds":[],
            "RequiredUpgradeIds":[]
        },
        {
            "EntryId":"WKPlacement_Deletion",
            "CategoryId":"Placement",
            "RequiredMechanicIds":[],
            "RequiredUpgradeIds":[]
        },
        {
            "EntryId":"WKPlacement_UndoRedo",
            "CategoryId":"Placement",
            "RequiredMechanicIds":[],
            "RequiredUpgradeIds":[]
        },
        {
            "EntryId":"WKPlacement_AreaSelection",
            "CategoryId":"Placement",
            "RequiredMechanicIds":[],
            "RequiredUpgradeIds":[]
        },
        {
            "EntryId":"WKPlacement_AreaDeletion",
            "CategoryId":"Placement",
            "RequiredMechanicIds":[],
            "RequiredUpgradeIds":[]
        },
        {
            "EntryId":"WKPlacement_Toolbar",
            "CategoryId":"Placement",
            "RequiredMechanicIds":[],
            "RequiredUpgradeIds":[]
        },
        {
            "EntryId":"WKPlacement_Mirroring",
            "CategoryId":"Placement",
            "RequiredMechanicIds":[],
            "RequiredUpgradeIds":[]
        },
        {
            "EntryId":"WKPlacement_SwitchingVariants",
            "CategoryId":"Placement",
            "RequiredMechanicIds":[],
            "RequiredUpgradeIds":[]
        },
        {
            "EntryId":"WKPlacement_ClearContents",
            "CategoryId":"Placement",
            "RequiredMechanicIds":[],
            "RequiredUpgradeIds":[]
        },
        {
            "EntryId":"WKPlacement_FloorVisibility",
            "CategoryId":"Placement",
            "RequiredMechanicIds":[],
            "RequiredUpgradeIds":[]
        },
        {
            "EntryId":"WKPlacement_Pipette",
            "CategoryId":"Placement",
            "RequiredMechanicIds":[],
            "RequiredUpgradeIds":[]
        },
        {
            "EntryId":"WKPlacement_SelectConnected",
            "CategoryId":"Placement",
            "RequiredMechanicIds":[],
            "RequiredUpgradeIds":[]
        },
        {
            "EntryId":"WKPlacement_FilterSelection",
            "CategoryId":"Placement",
            "RequiredMechanicIds":[],
            "RequiredUpgradeIds":[]
        },
        {
            "EntryId":"WKBelts_Intro",
            "CategoryId":"Belts",
            "RequiredMechanicIds":[],
            "RequiredUpgradeIds":[]
        },
        {
            "EntryId":"WKBelts_Placement",
            "CategoryId":"Belts",
            "RequiredMechanicIds":[],
            "RequiredUpgradeIds":[]
        },
        {
            "EntryId":"WKBelts_Checkpoints",
            "CategoryId":"Belts",
            "RequiredMechanicIds":[],
            "RequiredUpgradeIds":[]
        },
        {
            "EntryId":"WKBelts_Splitting",
            "CategoryId":"Belts",
            "RequiredMechanicIds":[],
            "RequiredUpgradeIds":[]
        },
        {
            "EntryId":"WKBelts_Merging",
            "CategoryId":"Belts",
            "RequiredMechanicIds":[],
            "RequiredUpgradeIds":[]
        },
        {
            "EntryId":"WKBelts_Lifts",
            "CategoryId":"Belts",
            "RequiredMechanicIds":[],
            "RequiredUpgradeIds":[]
        },
        {
            "EntryId":"WKBelts_IdealRatios",
            "CategoryId":"Belts",
            "RequiredMechanicIds":[],
            "RequiredUpgradeIds":[]
        },
        {
            "EntryId":"WKBelts_OverflowSplitter",
            "CategoryId":"Belts",
            "RequiredMechanicIds":[],
            "RequiredUpgradeIds":[]
        },
        {
            "EntryId":"WKBlueprints_Intro",
            "CategoryId":"Blueprints",
            "RequiredMechanicIds":[],
            "RequiredUpgradeIds":[]
        },
        {
            "EntryId":"WKBlueprints_Library",
            "CategoryId":"Blueprints",
            "RequiredMechanicIds":[],
            "RequiredUpgradeIds":[]
        },
        {
            "EntryId":"WKBlueprints_Sharing",
            "CategoryId":"Blueprints",
            "RequiredMechanicIds":[],
            "RequiredUpgradeIds":[]
        },
        {
            "EntryId":"WKBlueprints_Icons",
            "CategoryId":"Blueprints",
            "RequiredMechanicIds":[],
            "RequiredUpgradeIds":[]
        },
        {
            "EntryId":"WKBlueprints_Flipping",
            "CategoryId":"Blueprints",
            "RequiredMechanicIds":[],
            "RequiredUpgradeIds":[]
        },
        {
            "EntryId":"WKBlueprints_Folders",
            "CategoryId":"Blueprints",
            "RequiredMechanicIds":[],
            "RequiredUpgradeIds":[]
        },
        {
            "EntryId":"WKBlueprints_Toolbar",
            "CategoryId":"Blueprints",
            "RequiredMechanicIds":[],
            "RequiredUpgradeIds":[]
        },
        {
            "EntryId":"WKBlueprints_PasteLast",
            "CategoryId":"Blueprints",
            "RequiredMechanicIds":[],
            "RequiredUpgradeIds":[]
        },
        {
            "EntryId":"WKBlueprints_Cost",
            "CategoryId":"Blueprints",
            "RequiredMechanicIds":[],
            "RequiredUpgradeIds":[]
        },
        {
            "EntryId":"WKShapes_Shapes",
            "CategoryId":"Shapes",
            "RequiredMechanicIds":[],
            "RequiredUpgradeIds":[]
        },
        {
            "EntryId":"WKShapes_ShapeViewer",
            "CategoryId":"Shapes",
            "RequiredMechanicIds":[],
            "RequiredUpgradeIds":[]
        },
        {
            "EntryId":"WKShapes_Code",
            "CategoryId":"Shapes",
            "RequiredMechanicIds":[],
            "RequiredUpgradeIds":[]
        },
        {
            "EntryId":"WKShapes_Pins",
            "CategoryId":"Shapes",
            "RequiredMechanicIds":[],
            "RequiredUpgradeIds":[]
        },
        {
            "EntryId":"WKShapes_Crystals",
            "CategoryId":"Shapes",
            "RequiredMechanicIds":[],
            "RequiredUpgradeIds":[]
        },
        {
            "EntryId":"WKShapes_Predictions",
            "CategoryId":"Shapes",
            "RequiredMechanicIds":[],
            "RequiredUpgradeIds":[]
        },
        {
            "EntryId":"WKShapes_ShapeLayerLimit",
            "CategoryId":"Shapes",
            "RequiredMechanicIds":[],
            "RequiredUpgradeIds":[]
        },
        {
            "EntryId":"WKShapes_CreatingQuarters",
            "CategoryId":"Shapes",
            "RequiredMechanicIds":[],
            "RequiredUpgradeIds":[]
        },
        {
            "EntryId":"WKShapes_CreatingDiagonals",
            "CategoryId":"Shapes",
            "RequiredMechanicIds":[],
            "RequiredUpgradeIds":[]
        },
        {
            "EntryId":"WKShapes_Overhangs",
            "CategoryId":"Shapes",
            "RequiredMechanicIds":[],
            "RequiredUpgradeIds":[]
        },
        {
            "EntryId":"WKProcessing_Intro",
            "CategoryId":"Processing",
            "RequiredMechanicIds":[],
            "RequiredUpgradeIds":[]
        },
        {
            "EntryId":"WKProcessing_BuildingMode",
            "CategoryId":"Processing",
            "RequiredMechanicIds":[],
            "RequiredUpgradeIds":[]
        },
        {
            "EntryId":"WKProcessing_Floors",
            "CategoryId":"Processing",
            "RequiredMechanicIds":[],
            "RequiredUpgradeIds":[]
        },
        {
            "EntryId":"WKProcessing_Extractor",
            "CategoryId":"Processing",
            "RequiredMechanicIds":[],
            "RequiredUpgradeIds":[]
        },
        {
            "EntryId":"WKProcessing_HalfDestroyer",
            "CategoryId":"Processing",
            "RequiredMechanicIds":[],
            "RequiredUpgradeIds":[]
        },
        {
            "EntryId":"WKProcessing_Rotator",
            "CategoryId":"Processing",
            "RequiredMechanicIds":[],
            "RequiredUpgradeIds":[]
        },
        {
            "EntryId":"WKProcessing_Cutter",
            "CategoryId":"Processing",
            "RequiredMechanicIds":[],
            "RequiredUpgradeIds":[]
        },
        {
            "EntryId":"WKProcessing_PinPusher",
            "CategoryId":"Processing",
            "RequiredMechanicIds":[],
            "RequiredUpgradeIds":[]
        },
        {
            "EntryId":"WKProcessing_Swapper",
            "CategoryId":"Processing",
            "RequiredMechanicIds":[],
            "RequiredUpgradeIds":[]
        },
        {
            "EntryId":"WKProcessing_Stacker",
            "CategoryId":"Processing",
            "RequiredMechanicIds":[],
            "RequiredUpgradeIds":[]
        },
        {
            "EntryId":"WKFluids_Intro",
            "CategoryId":"Fluids",
            "RequiredMechanicIds":[],
            "RequiredUpgradeIds":[]
        },
        {
            "EntryId":"WKFluids_FluidMiners",
            "CategoryId":"Fluids",
            "RequiredMechanicIds":[],
            "RequiredUpgradeIds":[]
        },
        {
            "EntryId":"WKFluids_Pump",
            "CategoryId":"Fluids",
            "RequiredMechanicIds":[],
            "RequiredUpgradeIds":[]
        },
        {
            "EntryId":"WKFluids_Pipes",
            "CategoryId":"Fluids",
            "RequiredMechanicIds":[],
            "RequiredUpgradeIds":[]
        },
        {
            "EntryId":"WKFluids_FluidLaunchers",
            "CategoryId":"Fluids",
            "RequiredMechanicIds":[],
            "RequiredUpgradeIds":[]
        },
        {
            "EntryId":"WKFluids_SpacePipes",
            "CategoryId":"Fluids",
            "RequiredMechanicIds":[],
            "RequiredUpgradeIds":[]
        },
        {
            "EntryId":"WKFluids_Painting",
            "CategoryId":"Fluids",
            "RequiredMechanicIds":[],
            "RequiredUpgradeIds":[]
        },
        {
            "EntryId":"WKFluids_Mixing",
            "CategoryId":"Fluids",
            "RequiredMechanicIds":[],
            "RequiredUpgradeIds":[]
        },
        {
            "EntryId":"WKFluids_FluidTank",
            "CategoryId":"Fluids",
            "RequiredMechanicIds":[],
            "RequiredUpgradeIds":[]
        },
        {
            "EntryId":"WKFluids_CrystalGenerator",
            "CategoryId":"Fluids",
            "RequiredMechanicIds":[],
            "RequiredUpgradeIds":[]
        },
        {
            "EntryId":"WKFluids_ColorMode",
            "CategoryId":"Fluids",
            "RequiredMechanicIds":[],
            "RequiredUpgradeIds":[]
        },
        {
            "EntryId":"WKFluids_ColorBlindness",
            "CategoryId":"Fluids",
            "RequiredMechanicIds":[],
            "RequiredUpgradeIds":[]
        },
        {
            "EntryId":"WKIslands_SpacePlatforms",
            "CategoryId":"Islands",
            "RequiredMechanicIds":[],
            "RequiredUpgradeIds":[]
        },
        {
            "EntryId":"WKIslands_SpaceMode",
            "CategoryId":"Islands",
            "RequiredMechanicIds":[],
            "RequiredUpgradeIds":[]
        },
        {
            "EntryId":"WKIslands_PlatformLimit",
            "CategoryId":"Islands",
            "RequiredMechanicIds":[],
            "RequiredUpgradeIds":[]
        },
        {
            "EntryId":"WKIslands_Floors",
            "CategoryId":"Islands",
            "RequiredMechanicIds":[],
            "RequiredUpgradeIds":[]
        },
        {
            "EntryId":"WKIslands_ShapeMiners",
            "CategoryId":"Islands",
            "RequiredMechanicIds":[],
            "RequiredUpgradeIds":[]
        },
        {
            "EntryId":"WKIslands_SpaceBelts",
            "CategoryId":"Islands",
            "RequiredMechanicIds":[],
            "RequiredUpgradeIds":[]
        },
        {
            "EntryId":"WKIslands_SpaceBeltLifts",
            "CategoryId":"Islands",
            "RequiredMechanicIds":[],
            "RequiredUpgradeIds":[]
        },
        {
            "EntryId":"WKIslands_Foundations",
            "CategoryId":"Islands",
            "RequiredMechanicIds":[],
            "RequiredUpgradeIds":[]
        },
        {
            "EntryId":"WKIslands_ModularBuilds",
            "CategoryId":"Islands",
            "RequiredMechanicIds":[],
            "RequiredUpgradeIds":[]
        },
        {
            "EntryId":"WKTrains_Intro",
            "CategoryId":"Trains",
            "RequiredMechanicIds":[],
            "RequiredUpgradeIds":[]
        },
        {
            "EntryId":"WKTrains_Locomotives",
            "CategoryId":"Trains",
            "RequiredMechanicIds":[],
            "RequiredUpgradeIds":[]
        },
        {
            "EntryId":"WKTrains_Wagons",
            "CategoryId":"Trains",
            "RequiredMechanicIds":[],
            "RequiredUpgradeIds":[]
        },
        {
            "EntryId":"WKTrains_ShapeTransport",
            "CategoryId":"Trains",
            "RequiredMechanicIds":[],
            "RequiredUpgradeIds":[]
        },
        {
            "EntryId":"WKTrains_FluidTransport",
            "CategoryId":"Trains",
            "RequiredMechanicIds":[],
            "RequiredUpgradeIds":[]
        },
        {
            "EntryId":"WKTrains_Rails",
            "CategoryId":"Trains",
            "RequiredMechanicIds":[],
            "RequiredUpgradeIds":[]
        },
        {
            "EntryId":"WKTrains_TrainStops",
            "CategoryId":"Trains",
            "RequiredMechanicIds":[],
            "RequiredUpgradeIds":[]
        },
        {
            "EntryId":"WKTrains_TrainStations",
            "CategoryId":"Trains",
            "RequiredMechanicIds":[],
            "RequiredUpgradeIds":[]
        },
        {
            "EntryId":"WKTrains_TrainRoutes",
            "CategoryId":"Trains",
            "RequiredMechanicIds":[],
            "RequiredUpgradeIds":[]
        },
        {
            "EntryId":"WKTrains_SpacerWagons",
            "CategoryId":"Trains",
            "RequiredMechanicIds":[],
            "RequiredUpgradeIds":[]
        },
        {
            "EntryId":"WKTrains_SupporterEdition",
            "CategoryId":"Trains",
            "RequiredMechanicIds":[],
            "RequiredUpgradeIds":[]
        },
        {
            "EntryId":"WKWires_WiresSignals",
            "CategoryId":"Wires",
            "RequiredMechanicIds":[],
            "RequiredUpgradeIds":[]
        },
        {
            "EntryId":"WKWires_Truthiness",
            "CategoryId":"Wires",
            "RequiredMechanicIds":[],
            "RequiredUpgradeIds":[]
        },
        {
            "EntryId":"WKWires_ConstantSignal",
            "CategoryId":"Wires",
            "RequiredMechanicIds":[],
            "RequiredUpgradeIds":[]
        },
        {
            "EntryId":"WKWires_BeltFilter",
            "CategoryId":"Wires",
            "RequiredMechanicIds":[],
            "RequiredUpgradeIds":[]
        },
        {
            "EntryId":"WKWires_BeltReader",
            "CategoryId":"Wires",
            "RequiredMechanicIds":[],
            "RequiredUpgradeIds":[]
        },
        {
            "EntryId":"WKWires_PipeGate",
            "CategoryId":"Wires",
            "RequiredMechanicIds":[],
            "RequiredUpgradeIds":[]
        },
        {
            "EntryId":"WKWires_Button",
            "CategoryId":"Wires",
            "RequiredMechanicIds":[],
            "RequiredUpgradeIds":[]
        },
        {
            "EntryId":"WKWires_LogicGates",
            "CategoryId":"Wires",
            "RequiredMechanicIds":[],
            "RequiredUpgradeIds":[]
        },
        {
            "EntryId":"WKWires_Display",
            "CategoryId":"Wires",
            "RequiredMechanicIds":[],
            "RequiredUpgradeIds":[]
        },
        {
            "EntryId":"WKWires_VirtualProcessing",
            "CategoryId":"Wires",
            "RequiredMechanicIds":[],
            "RequiredUpgradeIds":[]
        },
        {
            "EntryId":"WKWires_ShapeAnalyzer",
            "CategoryId":"Wires",
            "RequiredMechanicIds":[],
            "RequiredUpgradeIds":[]
        },
        {
            "EntryId":"WKWires_WireCrossings",
            "CategoryId":"Wires",
            "RequiredMechanicIds":[],
            "RequiredUpgradeIds":[]
        },
        {
            "EntryId":"WKWires_WireTransmission",
            "CategoryId":"Wires",
            "RequiredMechanicIds":[],
            "RequiredUpgradeIds":[]
        },
        {
            "EntryId":"WKWires_GlobalTransmission",
            "CategoryId":"Wires",
            "RequiredMechanicIds":[],
            "RequiredUpgradeIds":[]
        },
        {
            "EntryId":"WKWires_MaM",
            "CategoryId":"Wires",
            "RequiredMechanicIds":[],
            "RequiredUpgradeIds":[]
        },
        {
            "EntryId":"WKVortexLTD_Handbook",
            "CategoryId":"VortexLTD",
            "RequiredMechanicIds":[],
            "RequiredUpgradeIds":[]
        },
        {
            "EntryId":"WKVortexLTD_VerticalClearance",
            "CategoryId":"VortexLTD",
            "RequiredMechanicIds":[],
            "RequiredUpgradeIds":[],
            "UnavailableIfLocked":True
        },
        {
            "EntryId":"WKVortexLTD_Stilts",
            "CategoryId":"VortexLTD",
            "RequiredMechanicIds":[],
            "RequiredUpgradeIds":[],
            "UnavailableIfLocked":True
        },
        {
            "EntryId":"WKVortexLTD_Pigment",
            "CategoryId":"VortexLTD",
            "RequiredMechanicIds":[],
            "RequiredUpgradeIds":[],
            "UnavailableIfLocked":True
        },
        {
            "EntryId":"WKVortexLTD_RailIncident",
            "CategoryId":"VortexLTD",
            "RequiredMechanicIds":[],
            "RequiredUpgradeIds":[],
            "UnavailableIfLocked":True
        },
        {
            "EntryId":"WKVortexLTD_NinthColor",
            "CategoryId":"VortexLTD",
            "RequiredMechanicIds":[],
            "RequiredUpgradeIds":[],
            "UnavailableIfLocked":True
        },
        {
            "EntryId":"WKVortexLTD_CrystalBrief",
            "CategoryId":"VortexLTD",
            "RequiredMechanicIds":[],
            "RequiredUpgradeIds":[],
            "UnavailableIfLocked":True
        },
        {
            "EntryId":"WKVortexLTD_CompletionNotice",
            "CategoryId":"VortexLTD",
            "RequiredMechanicIds":[],
            "RequiredUpgradeIds":[],
            "UnavailableIfLocked":True
        },
        {
            "EntryId":"WKVortexLTD_Anomaly221",
            "CategoryId":"VortexLTD",
            "RequiredMechanicIds":[],
            "RequiredUpgradeIds":[],
            "UnavailableIfLocked":True
        },
        {
            "EntryId":"WKVortexLTD_BoardMinutes",
            "CategoryId":"VortexLTD",
            "RequiredMechanicIds":[],
            "RequiredUpgradeIds":[],
            "UnavailableIfLocked":True
        },
        {
            "EntryId":"WKVortexLTD_VasquezLog",
            "CategoryId":"VortexLTD",
            "RequiredMechanicIds":[],
            "RequiredUpgradeIds":[],
            "UnavailableIfLocked":True
        },
        {
            "EntryId":"WKVortexLTD_Singularity",
            "CategoryId":"VortexLTD",
            "RequiredMechanicIds":[],
            "RequiredUpgradeIds":[],
            "UnavailableIfLocked":True
        },
        {
            "EntryId":"WKMisc_MapGeneration",
            "CategoryId":"Misc",
            "RequiredMechanicIds":[],
            "RequiredUpgradeIds":[]
        },
        {
            "EntryId":"WKMisc_Challenges",
            "CategoryId":"Misc",
            "RequiredMechanicIds":[],
            "RequiredUpgradeIds":[]
        },
        {
            "EntryId":"WKMisc_Difficulty",
            "CategoryId":"Misc",
            "RequiredMechanicIds":[],
            "RequiredUpgradeIds":[]
        },
        {
            "EntryId":"WKMisc_ConsoleCommands",
            "CategoryId":"Misc",
            "RequiredMechanicIds":[],
            "RequiredUpgradeIds":[]
        },
        {
            "EntryId":"WKMisc_Feedback",
            "CategoryId":"Misc",
            "RequiredMechanicIds":[],
            "RequiredUpgradeIds":[]
        },
        {
            "EntryId":"WKMisc_GameModes",
            "CategoryId":"Misc",
            "RequiredMechanicIds":[],
            "RequiredUpgradeIds":[]
        }
    ],
    [
        {
            "EntryId":"WKClassicRegularWelcome",
            "CategoryId":"Misc",
            "RequiredMechanicIds":[],
            "RequiredUpgradeIds":[]
        },
        {
            "EntryId":"WKClassicHardWelcome",
            "CategoryId":"Misc",
            "RequiredMechanicIds":[],
            "RequiredUpgradeIds":[]
        },
        {
            "EntryId":"WKClassicInsaneWelcome",
            "CategoryId":"Misc",
            "RequiredMechanicIds":[],
            "RequiredUpgradeIds":[]
        },
        {
            "EntryId":"WKClassicHexWelcome",
            "CategoryId":"Misc",
            "RequiredMechanicIds":[],
            "RequiredUpgradeIds":[]
        },
        {
            "EntryId":"WKTrains_VortexDelivery",
            "CategoryId":"Trains",
            "RequiredMechanicIds":[],
            "RequiredUpgradeIds":[]
        },
        {
            "EntryId":"WKClassicVortex_Vortex",
            "CategoryId":"Research",
            "RequiredMechanicIds":[],
            "RequiredUpgradeIds":[]
        },
        {
            "EntryId":"WKClassicVortex_ShapeRotation",
            "CategoryId":"Research",
            "RequiredMechanicIds":[],
            "RequiredUpgradeIds":[]
        },
        {
            "EntryId":"WKResearch_Milestones",
            "CategoryId":"Research",
            "RequiredMechanicIds":[],
            "RequiredUpgradeIds":[]
        },
        {
            "EntryId":"WKResearchClassic_SideTasks",
            "CategoryId":"Research",
            "RequiredMechanicIds":[],
            "RequiredUpgradeIds":[]
        },
        {
            "EntryId":"WKResearch_Shop",
            "CategoryId":"Research",
            "RequiredMechanicIds":[],
            "RequiredUpgradeIds":[]
        },
        {
            "EntryId":"WKResearch_ResearchPoints",
            "CategoryId":"Research",
            "RequiredMechanicIds":[],
            "RequiredUpgradeIds":[]
        },
        {
            "EntryId":"WKResearchClassic_PinTasks",
            "CategoryId":"Research",
            "RequiredMechanicIds":[],
            "RequiredUpgradeIds":[]
        },
        {
            "EntryId":"WKResearch_OperatorLevel",
            "CategoryId":"Research",
            "RequiredMechanicIds":[],
            "RequiredUpgradeIds":[]
        }
    ],
    [
        {
            "EntryId":"WKTradeStations_Overview",
            "CategoryId":"TradeStations",
            "RequiredMechanicIds":[],
            "RequiredUpgradeIds":[]
        },
        {
            "EntryId":"WKClassicTradeStations_RGB",
            "CategoryId":"TradeStations",
            "RequiredMechanicIds":[],
            "RequiredUpgradeIds":[]
        },
        {
            "EntryId":"WKClassicTradeStations_CMY",
            "CategoryId":"TradeStations",
            "RequiredMechanicIds":[],
            "RequiredUpgradeIds":[]
        },
        {
            "EntryId":"WKClassicTradeStations_WK",
            "CategoryId":"TradeStations",
            "RequiredMechanicIds":[],
            "RequiredUpgradeIds":[]
        },
        {
            "EntryId":"WKClassicTradeStations_VGA",
            "CategoryId":"TradeStations",
            "RequiredMechanicIds":[],
            "RequiredUpgradeIds":[]
        }
    ]
]
